name: Check Links

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * 5"

jobs:
    linkChecker:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Link Checker
          id: lychee
          uses: lycheeverse/lychee-action@v2.0.2
          with:
            args: --verbose --retry-wait-time 30 https://blockchain.netz39.de/
            fail: false # Don't fail action on broken links

        - name: Create Issue From File
          if: env.lychee_exit_code != 0
          uses: peter-evans/create-issue-from-file@v4
          with:
            title: Link Checker Report
            content-filepath: ./lychee/out.md
            labels: report, automated issue
